### ISSUE TITLE
No frame rendered after adding VideoSender to camera

### ISSUE THREAD

**Issue by fmoraes74** [anome/Unity-VideoOutput#2]
Title describes the issue I've seen. I get nothing displayed after adding VS to the main camera. Is there something I am missing?

**Comment by mto-anomes** [comment]
Hello,

To better understand your issue could you please answer these questions :
- Are you on Mac or Windows ?
- Are you trying to use Spout, Syphon, or NDI ?
- Does the plugin says in its UI "Running correctly" ?
- Which version of Unity you are using ?
- Is there any message appearing in the console such as errors or warnings ?

Thank you

**Comment by mto-anomes** [comment]
I am closing this issue following the release of v2. Please open a new one if you still encounter this issue with the v2.

Thank you.
