### ISSUE TITLE
 syphon sender (video sender) with HDRP settings? 

### ISSUE THREAD

**Issue by tomalouette** [anome/Unity-VideoOutput#3]

**Comment by tomalouette** [comment]
Hi, is it possible to use the video sender script in a HDRP Unity project? 
I try this on a 2019.15 unity project to Millumin and OBS.
The plugin is active and seem to make the job in the camera. 
But there is not output, by syphon (metal) or NDI.
And if i switch the HD render Pipeline setting to none, the signal is ok.

I've tried the KlakSyphon too, and it doesn't support the HDR either
Thanks for all

**Comment by tomalouette** [comment]
Hi,
Any answer?
Best

**Comment by mto-anomes** [comment]
Hi Tom,

HDRP is not implemented at the moment

**Comment by mto-anomes** [comment]
Hi, 

the V2 supports HDRP and URP and should resolve your issue
