### ISSUE TITLE
Failed Builds: ArugmentException from UnityEditor 

### ISSUE THREAD

**Issue by kdittle** [anome/Unity-VideoOutput#4]
I've noticed an issue when I attempt to build where I'm getting an Argument Exception and the build fails. The following is the error:

`ArgumentException: The Assembly UnityEditor is referenced by UVSEditor ('Assets/UnityVideoSender/Managed/UVSEditor.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at <af78ad00a40d4f61b82afc6cafb0a416>:0)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at <af78ad00a40d4f61b82afc6cafb0a416>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

Repro Steps:
Create empty 3D project in Unity 2019.4.0f1
Import UnityVideoSender_v1_Windows.unitypackage
Open Build Settings
Add DEMO Scene to build scenes
Build
--FAIL--

**Comment by mto-anomes** [comment]
Hello Kyle,

Thank you for reporting the problem, I will look at it shortly

**Comment by mto-anomes** [comment]
Hello Kyle,

I've made a few tests and the 2019.4.0f1 is a bit unstable for the moment. I wouldn't recommend using it right now. We will support it later.

Maxime

**Comment by kdittle** [comment]
Thank you for looking into it.
